[access]
username="root"
password="root"
# initPassword = "myOldPassword"
# host="localhost"
# port=3306
socket="/var/run/mysqld/mysqld.sock"

[[database]]
name = "oleg_test"

[[user]]
username = "oleg"
network = "10.%"
hashedPassword = "*F41E614E894A46E0FB7317B1C8CB6CEA97415C7B"
[[user.permissions]]
database = "oleg%"
table = "*"
privileges = ["SELECT", "UPDATE"]
[[user.permissions]]
database = "qwerty"
table = "*"
privileges = ["SELECT"]

[[user]]
username = "root"
network = "127.0.0.1"
password = "root"
grantOption = true
[[user.permissions]]
database = "*"
table = "*"
privileges = ["ALL PRIVILEGES"]


[[user]]
username = "root"
password = "root"
network = "localhost"
grantOption = true
[[user.permissions]]
database = "*"
table = "*"
privileges = ["ALL PRIVILEGES"]