[access]
username="root"
password="root"
# initPassword = "myOldPassword"
host="localhost"
port=3306

[[database]]
name = "information_schema"
[[database]]
name = "mysql"
[[database]]
name = "performance_schema"

[[user]]
username = "oleg"
network = "10.%"
password = "oleg"
database = "oleg%"
table = "*"
privileges = ["USAGE"]

[[user]]
username = "root"
network = "127.0.0.1"
password = "root"
database = "*"
table = "*"
privileges = ["ALL PRIVILEGES"]
grantOption = true

[[user]]
username = "root"
password = "root"
network = "localhost"
database = "*"
table = "*"
privileges = ["ALL PRIVILEGES"]
grantOption = true