[[database]]
name = "information_schema"
[[database]]
name = "mysql"
[[database]]
name = "performance_schema"

[[user]]
username = "oleg"
host = "10.%"
password = "*F41E614E894A46E0FB7317B1C8CB6CEA97415C7B"
database = "oleg"
table = "*"
privileges = ["USAGE"]

[[user]]
username = "root"
host = "127.0.0.1"
password = "*81F5E21E35407D884A6CD4A731AEBFB6AF209E1B"
database = "*"
table = "*"
privileges = ["ALL PRIVILEGES"]
grantOption = true

[[user]]
username = "root"
host = "localhost"
password = "*81F5E21E35407D884A6CD4A731AEBFB6AF209E1B"
database = "*"
table = "*"
privileges = ["ALL PRIVILEGES"]
grantOption = true